spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:32768/postgres
spring.datasource.username=postgres
spring.datasource.password=postgrespw
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=G&*JEyoikhTR7NJT7uJKMftr&(Oh%5672@7o890-nh^fg5dvhn995^Rg8_=<UIui*TR%$&Ibg%7(JfW#346*(HF%T^6789d
spring.security.filter.order=10

spring.mail.username=kamil

password.seed=pcUURSGHASBGFYUAyo76I76Fi7f656Du6dTYkKkykgYFVkcdhxzhedXXZJxkm5478xv3svjvYAFSD634837Gud6dh46G67iBDw2113yJ0

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB