spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:32768/postgres
spring.datasource.username=postgres
spring.datasource.password=postgrespw
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=G&*JEyoikhTR7NJT7uJKMftr&(Oh%5672@7o890-nh^fg5dvhn995^Rg8_=<UIui*TR%$&Ibg%7(JfW#346*(HF%T^6789d
spring.security.filter.order=10

spring.mail.username=kamil

password.seed=R3UqSkV5b2lraFRSN05KVDd1SktNZnRyJihPaCU1NjcyQDdvODkwLW5oXmZnNWR2aG45OTVeUmc4Xz08VUl1aSpUUiUkJkliZyU3KEpmVyMzNDYqKEhGJVReNjc4OWQ=

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB